### ISSUE TITLE
❯ quarto use template ihrke/mdpi.tex Extension not found in local or remote sources

### ISSUE THREAD

**Issue by Younthing** [ihrke/mdpi#1]
❯ quarto use template ihrke/mdpi.tex
Extension not found in local or remote sources

**Comment by r-scotti** [comment]
I have the same problem

**Comment by Younthing** [comment]
> I have the same problem with
> 
> ```
> $ quarto add ihrke/mdpi
> Extension not found in local or remote sources
> ```

Yes, I tried `quarto add quarto-journals/acm`, and it works fine.

**Comment by raffdoc** [comment]
Same for me.

**Comment by ihrke** [comment]
Thanks for letting me know! Not sure what changed but the following command should work:

```
quarto add https://github.com/ihrke/mdpi
```
Will change the README to reflect this.
